import { PhysicsParams, RecordedSession } from "../types";
import JSZip from "jszip";

// Helper to trigger download
const downloadBlob = (blob: Blob, filename: string) => {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportVideo = (session: RecordedSession) => {
  if (!session.videoBlob) return;
  const filename = `snaplock_video_${session.startTime.replace(/:/g, '-')}.webm`;
  downloadBlob(session.videoBlob, filename);
};

export const exportCOCO = async (session: RecordedSession) => {
  const categories = session.params.assetGroups.map((ag, idx) => ({
    id: idx + 1, // 1-based index for COCO
    name: ag.name,
    supercategory: "physics_object"
  }));

  const images = session.frames.map((frame, idx) => ({
    id: idx,
    width: session.resolution.width,
    height: session.resolution.height,
    file_name: `frame_${String(idx).padStart(5, '0')}.png`, // Matches what user would extract from video
    license: 1,
    date_captured: new Date(frame.timestamp).toISOString()
  }));

  let annotationId = 1;
  const annotations = session.frames.flatMap((frame, imageIdx) => {
    return frame.objects.map(obj => ({
      id: annotationId++,
      image_id: imageIdx,
      category_id: obj.classId, // Mapped from asset group index
      bbox: [obj.x, obj.y, obj.width, obj.height], // COCO format: [x,y,width,height]
      area: obj.width * obj.height,
      segmentation: [], // Empty for bounding box only
      iscrowd: 0
    }));
  });

  const coco = {
    info: {
      year: new Date().getFullYear(),
      version: "1.0",
      description: "SnapLock Synthetic Dataset",
      contributor: "SnapLock AI",
      date_created: new Date().toISOString()
    },
    licenses: [{ id: 1, name: "CC BY 4.0", url: "https://creativecommons.org/licenses/by/4.0/" }],
    images,
    annotations,
    categories
  };

  const blob = new Blob([JSON.stringify(coco, null, 2)], { type: 'application/json' });
  downloadBlob(blob, `snaplock_coco_${Date.now()}.json`);
};

export const exportYOLO = async (session: RecordedSession) => {
  const zip = new JSZip();
  const folder = zip.folder("labels");
  
  // Create data.yaml
  const classNames = session.params.assetGroups.map(g => g.name);
  const yamlContent = `
train: ../train/images
val: ../valid/images
nc: ${classNames.length}
names: [${classNames.map(n => `'${n}'`).join(', ')}]
  `.trim();
  zip.file("data.yaml", yamlContent);

  // Generate label files per frame
  session.frames.forEach((frame, idx) => {
    const lines = frame.objects.map(obj => {
      // YOLO format: <class> <x_center> <y_center> <width> <height> (normalized 0-1)
      const x_center = (obj.x + obj.width / 2) / session.resolution.width;
      const y_center = (obj.y + obj.height / 2) / session.resolution.height;
      const w_norm = obj.width / session.resolution.width;
      const h_norm = obj.height / session.resolution.height;
      
      // Class ID in YOLO is 0-indexed
      return `${obj.classId - 1} ${x_center.toFixed(6)} ${y_center.toFixed(6)} ${w_norm.toFixed(6)} ${h_norm.toFixed(6)}`;
    });
    
    if (folder) {
        folder.file(`frame_${String(idx).padStart(5, '0')}.txt`, lines.join('\n'));
    }
  });

  const blob = await zip.generateAsync({ type: "blob" });
  downloadBlob(blob, `snaplock_yolo_${Date.now()}.zip`);
};

export const generateReport = async (session: RecordedSession) => {
  const report = `
# SnapLock Simulation Audit Report

**Date:** ${new Date().toLocaleString()}
**Duration:** ${((new Date(session.endTime).getTime() - new Date(session.startTime).getTime()) / 1000).toFixed(2)} seconds
**Frames Captured:** ${session.frames.length}
**Resolution:** ${session.resolution.width}x${session.resolution.height}

## Physics Configuration
- **Gravity:** X=${session.params.gravity.x}, Y=${session.params.gravity.y}, Z=${session.params.gravity.z}
- **Time Step:** ${session.params.simulation.timeStep}s
- **Substeps:** ${session.params.simulation.substeps}

## Asset Manifest
${session.params.assetGroups.map((g, i) => `
### Group ${i + 1}: ${g.name}
- **Type:** ${g.shape}
- **Count:** ${g.count}
- **Mass:** ${g.mass}kg
- **Friction:** ${g.friction}
- **Restitution:** ${g.restitution}
`).join('\n')}

## Environment
- **Floor Color:** ${session.params.scene.environment.floorColor}
- **Lighting:** Ambient=${session.params.scene.environment.ambientLightIntensity}, Directional=${session.params.scene.environment.directionalLightIntensity}

---
Generated by SnapLock AI Physics Engine
  `.trim();

  const blob = new Blob([report], { type: 'text/markdown' });
  downloadBlob(blob, `snaplock_report_${Date.now()}.md`);
};